[versions]
minecraft = "1.21"
yarn-mappings = "1.21+build.3"
fabric-loader = "0.15.11"
fabric-api = "0.102.0+1.21"

loom = "1.14-SNAPSHOT"

baritone = "1.21-SNAPSHOT"
sodium = "mc1.21-0.8.0-fabric"
lithium = "mc1.21-0.21.1-fabric"
iris = "1.10.2+1.21-fabric"
modmenu = "15.0.0"

orbit = "0.2.4"
starscript = "0.2.5"
discordipc = "1.1"
reflections = "0.10.2"
netty = "4.2.7.Final"
viafabricplus = "4.4.0"
waybackauthlib = "1.0.1"
